---
title: "DAEDALUS: economic variables"
date: "20 June, 2023"
geometry: margin=1cm
header-includes:
  - \usepackage{eso-pic,graphicx,transparent}
  - \usepackage{fancyhdr}
  - \usepackage{lastpage}
output:
  bookdown::html_document2: 
    toc: true
    keep_md: true
  bookdown::pdf_document2: 
    toc_depth: 5
    toc_float: true
    number_sections: true
    keep_tex: true
  md_document:
    variant: markdown_github
  bookdown::word_document2: default
  bookdown::github_document2:
    toc: true
    appendix: true
    fig_caption: yes
    number_sections: yes
    pandoc_args: --webtex
always_allow_html: yes 
bibliography: 
  - "DAEDALUS.bib"
---

\fancypagestyle{plain}{%
  \renewcommand{\headrulewidth}{0pt}%
  \fancyhf{}%
  \fancyfoot[R]{\footnotesize \thepage}
  \setlength\footskip{0pt}
}
\pagestyle{plain}
  
\AddToShipoutPictureFG{
  \AtPageCenter{% or \AtTextCenter
    \makebox[0pt]{\rotatebox[origin=c]{45}{%
      \scalebox{7}{\texttransparent{0.3}{PRELIMINARY DRAFT}}%
    }}
  }
}



      country Country.Code internet
110 Indonesia          IDN 47.69065

\newpage

# Introduction

The objective of the proposed work is to use scenario modelling to ascertain the vulnerability of a country to a hypothetical pandemic across several dimensions. The dimensions of vulnerability we consider here include economic loss, life loss, and education loss. The variables we consider as potential indicators of vulnerability relate to the reliance of the economy on two economic sectors, and the level of digitization and associated capacity to provide home-based work and education.  

We simulate hypothetical pandemics caused by one of seven respiratory pathogens, each with a disease profile informed by a past epidemic. We use the integrated epi-econ model DAEDALUS developed in our group for estimating the benefit of pandemic preparedness (P2) [@Haw2020]. The scenarios are informed by real-world demographic, societal and economic data for up to 197 countries. We evaluate outcomes for four mitigation strategies ("unmitigated", "adaptive economic closures", "school closures", and "elimination"). 

The impacts we project are losses to life, to education, and to GDP. We assess the impacts of the four variables of interest on the outcomes using value-of-information methods in order to identify which variables most influence outcomes, and in what circumstances.


# Methods

## Scenarios

The seven pathogen profiles include influenza and coronaviruses, and are based on past epidemics. Influenza virus profiles correspond to pandemics of the years 1918, 1957 and 2009. Coronavirus profiles correspond to SARS-CoV-1 and SARS-CoV-2, with three profiles: one, corresponding to variants that predated the variant-of-concern nomenclature (which we label "pre-Alpha"), and one each for the Delta and Omicron variants.

The four mitigation strategies are "unmitigated", "adaptive economic closures", "school closures", and "elimination". In the unmitigated strategy, no aversive actions are taken. With adaptive economic closures, sectors close according to a pre-specified programme when hospital occupancy approaches its capacity. With school closures, schools remain closed and other economic sectors have reduced operations. With the elimination strategy, stringent economic closures are maintained until case numbers can be contained by a testing programme. All economic configuration profiles are based on GVA profiles observed in 2020 (OECD), where the monthly GVA of a sector relative to its value one year prior is interpreted as the degree to which it was open. 

We consider three stylised "countries" and parametrise models using data from constituent countries according to the World Bank income-classification categories:

 - LLMIC, using inputs from LICs and LMICs
 - MIC, using inputs from LMICs and UMICs
 - HIC, using inputs from HICs


## Outcomes

The outcomes of the model are:

 1. Number of deaths (by four age groups)
 2. GDP loss
 3. Education loss
 
Numbers of deaths are translated into years of life lost (YLL). This takes into account the life expectancy of each person who dies. YLLs are valued using the value of a statistical life, which we estimate as being 160 times GDP per capita [@Robinson2019].

GDP loss is estimated as the total GDP - the sum of GVA across all sectors, scaled by how open they are across the year - divided by the value of GDP when all sectors are completely open all the time.

Education loss takes into account the extent to which schools are closed, as well as the effectiveness of provision for remote learning. We estimate this using internet coverage as a proxy (that is, we do not take into account education that can be delivered by TV or radio). Education loss is valued by taking into consideration life-long earning losses, following [@Psacharopoulos2021a]. 

We report these outcomes as a percentage of GDP (for the year prior to the pandemic -- here, 2019). All three outcomes (once a valuation is applied) are linear functions of GDP, and therefore results are all comparable across countries. The time horizon in the simulation is one year.



## Modelling

The integrated epi-econ model is used to project economic and epidemic outcomes. The epidemiological model is a population-structured compartmental SEIR model. It takes many inputs, including pathogen natural history parameters (such as R$_0$, case-fatality rates, etc) and population parameters (such as age structure, contact rates, etc). The economic model takes as input the GVA per sector, which uses the OECD classification of 45 economic sectors. Both models take as input the economic configuration over time: this is the extent to which each sector is open in each period. A sector is open to a maximum amount of 100%, when its full monthly GVA value is realised. If a sector is open to 50%, it contributes 50% of its maximum GVA for that period. In the epidemic model, contacts associated with that sector -- between workers, from workers to consumers, and between consumers -- are likewise scaled down.

The economic model is very simple: we do not model interdependencies between sectors, and the only way in which country interdependencies are taken into account is via changes to tourism which manifest in the "food and accommodation services" sector (see Section \@ref(impact-of-tourism)). We do not model seasonality or allow for sectors to grow (either in GDP or in workforce).

We generate a distribution over outcomes through sampling inputs. This distribution represents a catalogue of synthetic countries whose characteristics are randomly taken from candidate countries. By examining the relationships between inputs and outputs, we can identify the inputs that most drive uncertainty in outputs as encoded by our model or, equivalently, which inputs are the best predictors of the outcome(s), independently of all other variables.

We include uncertainty in as many parameters as possible. We sample from specified distributions, or sample with replacement from a discrete set of candidate options, where the candidate options are the values belonging to countries in the income group. 

Parameter distributions are independent of each other (with the exception of loss in tourism, where the size of the sector is related to the fraction of tourism that comes in from abroad (see Section \@ref(loss-of-international-tourists))). This means that any relationships we uncover between input and output within an income group will be causal, and we will not discover any factors that are "indicative" by association. (Between income groups there are many systematic differences in inputs and learning which of those drives the differences in outcomes is part of the ongoing development of the model.)

### Data sources

1. Workforce: ILO
2. GVA: OECD
3. Closure configurations: GVA 2020 for UK, Australia, Indonesia (OECD)
4. Contact matrices: [@Prem2021], [@Beraud2015]
5. Work from home: [@Gottlieb2021]
6. Hospital capacity: World Bank / OECD
7. Response time: Blavatnik 2022
8. Testing rate: 
9. Testing start time: 
10. Mobility: Our World in Data/Wang et al., 2022
11. Life expectancy: IHME?
12. Population: 
13. Tourism data: https://www.unwto.org/tourism-data/international-tourism-and-covid-19
14. International tourism: https://www.unwto.org/tourism-statistics/key-tourism-statistics
15. Internet coverage: World Bank
16. Labour share of GDP: [@Inklaar2013]



## Value of information



We assess the impacts of four parameters that relate to economic indicators:

 1. Agricultural GVA as a proportion of GDP
 2. Tourism GVA as a proportion of GDP
 3. Proportional of tourism that comes from abroad
 4. Internet coverage


We use value-of-information methods to quantify these relationships. Specifically, we estimate the expected value of partial perfect information (EVPPI), which is the expected gain (in terms of reduction of uncertainty in the outcome) of knowing a parameter (or set of parameters) perfectly [@Jackson2021]. Equivalently, and in terms of identifying indicators of vulnerability, it tells us which parameters best predict the outcome.

Value of information is a decision-theoretic quantity. We estimate it using the R package **voi**. Intuitively, EVPPI functions in a similar way to correlation. In the case of a linear relationship between one input and one output, the computation of EVPPI is essentially the same as that of a correlation. EVPPI extends a simple correlation analysis in two ways relevant to the results presented: 1) nonlinear relationships are also captured, and 2) we can assess the EVPPI of a set of parameters. EVPPI allows us to identify influential parameters. Once identified, relationships between the influential parameter (sets) and outcomes need to be examined independently in order to understand the nature of the relationship.

Finally, we can use mutual information (MI, via the R package **infotheo**) to assess mutual information between inputs and outputs. What MI offers beyond EVPPI is that it takes into account also how *likely* it is that the input parameter occupies a space where it is influential.

\newpage

# Results 

## Distributions over outcomes

Distributions over costs associated with the first year of an outbreak of SARS-CoV-2 (with parameters corresponding to variants arising before alpha) are shown in Figure \@ref(fig:prealpha) for three income levels and four mitigation strategies. Each shape represents the probability density made up of the sampled values for outcomes: the most likely value to take is where the figure is widest. The tip of the tail indicates the highest value sampled, after which point the density is 0.

These distributions show that vulnerability to a pandemic depends on a country's income level together with its mitigation strategy. For example, the elimination strategy appears to have the lowest distribution for overall cost for HICs among all strategies, whereas it appears no lower for MICs and perhaps higher for LLMICs. This will be because of the factors that vary systematically across countries of different income levels. Likewise, the heavier tails in the distributions for YLLs for HICs is likely due to the age distributions in HICs being heavier in older ages. These cross-country differences are one of the focuses of the development of the model.





<div class="figure">
<img src="p2_files/figure-html/prealpha-1.png" alt="Model results for pre-Alpha variants of SARS-CoV-2."  />
<p class="caption">(\#fig:prealpha)Model results for pre-Alpha variants of SARS-CoV-2.</p>
</div>


<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>(\#tab:tabres)Results for all scenarios shown. Mean values and 95% prediction intervals. \label{tab:tabres}</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Strategy </th>
   <th style="text-align:left;"> Income group </th>
   <th style="text-align:left;"> Total costs </th>
   <th style="text-align:left;"> YLLs </th>
   <th style="text-align:left;"> Education </th>
   <th style="text-align:left;"> GDP </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> No Closures </td>
   <td style="text-align:left;"> LLMIC </td>
   <td style="text-align:left;"> 50.9 (0, 360.1) </td>
   <td style="text-align:left;"> 47.8 (0, 354.7) </td>
   <td style="text-align:left;"> 0.4 (0, 1.2) </td>
   <td style="text-align:left;"> 2.7 (0, 11.2) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> School Closures </td>
   <td style="text-align:left;"> LLMIC </td>
   <td style="text-align:left;"> 61.9 (0, 340.6) </td>
   <td style="text-align:left;"> 34.3 (0, 287) </td>
   <td style="text-align:left;"> 23.3 (0, 83.6) </td>
   <td style="text-align:left;"> 4.3 (0, 18) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Economic Closures </td>
   <td style="text-align:left;"> LLMIC </td>
   <td style="text-align:left;"> 51.9 (0, 312.3) </td>
   <td style="text-align:left;"> 27 (0, 243) </td>
   <td style="text-align:left;"> 14.6 (0, 68.1) </td>
   <td style="text-align:left;"> 10.3 (0, 31.9) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Elimination </td>
   <td style="text-align:left;"> LLMIC </td>
   <td style="text-align:left;"> 57.6 (0, 313.7) </td>
   <td style="text-align:left;"> 26.2 (0, 241.5) </td>
   <td style="text-align:left;"> 19.7 (0, 79) </td>
   <td style="text-align:left;"> 11.6 (0, 33.7) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> No Closures </td>
   <td style="text-align:left;"> MIC </td>
   <td style="text-align:left;"> 52.9 (0, 367) </td>
   <td style="text-align:left;"> 50.7 (0, 360.4) </td>
   <td style="text-align:left;"> 0.2 (0, 0.6) </td>
   <td style="text-align:left;"> 2 (0, 7.1) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> School Closures </td>
   <td style="text-align:left;"> MIC </td>
   <td style="text-align:left;"> 51.5 (0, 310.2) </td>
   <td style="text-align:left;"> 35.9 (0, 280.8) </td>
   <td style="text-align:left;"> 11.8 (0, 45.7) </td>
   <td style="text-align:left;"> 3.8 (0, 13.7) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Economic Closures </td>
   <td style="text-align:left;"> MIC </td>
   <td style="text-align:left;"> 43.5 (0, 263.9) </td>
   <td style="text-align:left;"> 27.9 (0, 223) </td>
   <td style="text-align:left;"> 6.6 (0, 33.4) </td>
   <td style="text-align:left;"> 8.9 (0, 28.7) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Elimination </td>
   <td style="text-align:left;"> MIC </td>
   <td style="text-align:left;"> 52.4 (0, 263.6) </td>
   <td style="text-align:left;"> 25.3 (0, 220.4) </td>
   <td style="text-align:left;"> 13 (0, 43.1) </td>
   <td style="text-align:left;"> 14.1 (0, 30.7) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> No Closures </td>
   <td style="text-align:left;"> HIC </td>
   <td style="text-align:left;"> 40.7 (0, 315) </td>
   <td style="text-align:left;"> 39 (0, 311.3) </td>
   <td style="text-align:left;"> 0 (0, 0.1) </td>
   <td style="text-align:left;"> 1.6 (0, 5.8) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> School Closures </td>
   <td style="text-align:left;"> HIC </td>
   <td style="text-align:left;"> 29.2 (0, 209.2) </td>
   <td style="text-align:left;"> 23.5 (0, 194.3) </td>
   <td style="text-align:left;"> 2.8 (0, 11.4) </td>
   <td style="text-align:left;"> 3 (0, 10.3) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Economic Closures </td>
   <td style="text-align:left;"> HIC </td>
   <td style="text-align:left;"> 23.7 (0, 153.5) </td>
   <td style="text-align:left;"> 16.2 (0, 125.9) </td>
   <td style="text-align:left;"> 1.2 (0, 7.5) </td>
   <td style="text-align:left;"> 6.3 (0, 25.9) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Elimination </td>
   <td style="text-align:left;"> HIC </td>
   <td style="text-align:left;"> 26.5 (0, 133.4) </td>
   <td style="text-align:left;"> 10 (0, 99) </td>
   <td style="text-align:left;"> 3.4 (0, 11.2) </td>
   <td style="text-align:left;"> 13.1 (0, 29.6) </td>
  </tr>
</tbody>
</table>


“If a hypothetical low- or lower-middle income country that relies to 3% on tourism for their national income experienced a pandemic with a similar profile to the Spanish Flu, what would be the number of deaths, the loss in GDP, and the loss of in-person schooling were the country to rely on an elimination strategy? What would the impact be if the country relied to 6% on tourism?”  




At 3%, life-year loss is expected to be 22.55% of GDP (95%PI 0, 166.21). Education loss is expected to be 19.93% of GDP (95%PI 0, 74.58). GDP loss is expected to be 10.75% of GDP (95%PI 0, 27.93).

At 6%, life-year loss is expected to be 30.74% of GDP (95%PI 0, 295.49). Education loss is expected to be 20.64% of GDP (95%PI 0, 85.1). GDP loss is expected to be 12.05% of GDP (95%PI 0, 32.15).

Here, the uncertainty in model results swamps the difference in expected values across all outcomes.


\newpage

## Value of information

The value of information associated with a number of parameters for all costs considered is shown in Figure \@ref(fig:voi). The costs are listed down the y axis. Parameters and parameter groups are along the x axis. Colours indicate the extent to which uncertainty in the input(s) are driving uncertainty in the outcome, with lighter colours representing greater impact.

The first four items on the x axis are the four independent variables: size of the agriculture sector, size of the food and accommodation services sector, fraction of tourism coming from abroad, and internet coverage. While the two parameters driving tourism are impactful on GDP loss, particularly for strategies light on economic closures, they have little impact on total costs. (This relationship is also driven by the distribution of the food and accommodation sector contribution to GVA: the mutual information appears a more balanced metric (Figure \@ref(fig:mi)).) Meanwhile, internet coverage has modest impacts, particularly on education loss and for strategies that employ school closures.

The EVPPI (and MI) for tourism is high, particularly for lower-income countries because tourism can make up a large part of GDP, and particularly for strategies light on economic closure because then the only sector suffering a shortfall is the Food and accommodation services sector.

The next two items on the x axis are parameter groups. First, both sectors. Second, both tourism parameters. The grouping of parameters shows their combined impact on outcomes, which can be greater than the sum of their individual impacts.

The next columns do not correspond to the "independent variables" of interest but might be expected to influence outcomes: fraction of population who are school age, fraction of population who are in the oldest age group, population size, rate of testing, GDP, $R_0$ and maximum hospital capacity. $R_0$ in particular drives a lot of uncertainty in costs, primarily through YLLs. 

The final four items on the x axis are groups of variables: both age groups; two social-distancing parameters; hospital capacity, the fraction of the population aged 65 and over, and R$_0$; and testing parameters, response time, and R$_0$. 

Some distributions in Figure \@ref(fig:prealpha) are bimodal. For example, GDP loss under the Economic Closures strategy have peaks in density close to zero and also far from zero, with a low-density region in between. Here, in some samples (low GDP loss), the epidemic was not severe enough to warrant closures. This could be because R$_0$ was low, because hospital capacity was high, or both. Similarly, under the Elimination strategy, there is an area of high density at higher costs where the strategy does not work: due to R$_0$ being high, and/or the capacity to test being low, case numbers are not brought low enough and severe economic closures persist throughout, leading to high GDP loss.

These relationships are identified in the value-of-information analyses: the last two columns show value of information for R$_0$, fraction of population aged 65 and over and hospital capacity combined, and R$_0$, testing parameters and social-distancing parameters combined. These variables together explain much of the variance in GDP loss for the Economic Closures and Elimination strategies, respectively.


<div class="figure">
<img src="p2_files/figure-html/voi-1.png" alt="\footnotesize Value of information for pre-Alpha variants of SARS-CoV-2. First four columns: individual parameters of interest (agricultural sector as % of GDP, Food and accommodation services sector as % of GDP, international tourism as % of toursim, internet coverage). Next two columns: pairs of parameters of interest (both sectors, both tourism-related parameters). Next 11 columns: other random variables (fraction of population school age, fraction of population age 65 and over, population size, GDP, hospital capacity, testing rate, testing start time, government response time, social distancing minimum, social distancing responsiveness to case numbers, R$_0$). Final four columns: combinations of random variables (both age fractions, both social distancing parameters, hospital capacity + elders population + R$_0$, testing parameters + social distancing parameters + R$_0$)."  />
<p class="caption">(\#fig:voi)\footnotesize Value of information for pre-Alpha variants of SARS-CoV-2. First four columns: individual parameters of interest (agricultural sector as % of GDP, Food and accommodation services sector as % of GDP, international tourism as % of toursim, internet coverage). Next two columns: pairs of parameters of interest (both sectors, both tourism-related parameters). Next 11 columns: other random variables (fraction of population school age, fraction of population age 65 and over, population size, GDP, hospital capacity, testing rate, testing start time, government response time, social distancing minimum, social distancing responsiveness to case numbers, R$_0$). Final four columns: combinations of random variables (both age fractions, both social distancing parameters, hospital capacity + elders population + R$_0$, testing parameters + social distancing parameters + R$_0$).</p>
</div>


\enlargethispage{4\baselineskip}

<div class="figure">
<img src="p2_files/figure-html/mi-1.png" alt="Mutual information (MI) for pre-Alpha variants of SARS-CoV-2."  />
<p class="caption">(\#fig:mi)Mutual information (MI) for pre-Alpha variants of SARS-CoV-2.</p>
</div>


\newpage

To understand the relationship between a parameter and an outcome, e.g. whether the relationship is linear and increasing or decreasing, whether it is nonlinear, whether it is driven by extreme values, they must be plotted against each other. Likewise, a relationship between a parameter pair and an outcome can be plotted, e.g. Figure \@ref(fig:tourismgdp): for middle-income countries in a pre-Alpha SARS-CoV-2 pandemic with the "No Closures" strategy, GDP loss is greatest when both the food and accommodation services GVA as fraction of GDP and international tourism as a fraction of tourism are high.


<div class="figure">
<img src="p2_files/figure-html/interneted-1.png" alt="Relationship between internet coverage and education losses for middle-income countries in a Delta SARS-CoV-2 pandemic with the &quot;School Closures&quot; strategy."  />
<p class="caption">(\#fig:interneted)Relationship between internet coverage and education losses for middle-income countries in a Delta SARS-CoV-2 pandemic with the "School Closures" strategy.</p>
</div>

<div class="figure">
<img src="p2_files/figure-html/tourismsecgdp-1.png" alt="Relationship between the &quot;tourism sector&quot; size and GDP loss for middle-income countries in a pre-Alpha SARS-CoV-2 pandemic with the &quot;No Closures&quot; strategy."  />
<p class="caption">(\#fig:tourismsecgdp)Relationship between the "tourism sector" size and GDP loss for middle-income countries in a pre-Alpha SARS-CoV-2 pandemic with the "No Closures" strategy.</p>
</div>

<div class="figure">
<img src="p2_files/figure-html/tourismgdp-1.png" alt="Relationship between tourism parameters and GDP loss for middle-income countries in a pre-Alpha SARS-CoV-2 pandemic with the &quot;No Closures&quot; strategy."  />
<p class="caption">(\#fig:tourismgdp)Relationship between tourism parameters and GDP loss for middle-income countries in a pre-Alpha SARS-CoV-2 pandemic with the "No Closures" strategy.</p>
</div>



\newpage


# Conclusions

Using simulation modelling, we have projected distributions of epidemic losses -- of life, GDP, and education -- for seven pathogenic profiles, four stylised mitigation strategies, and three levels of country income. We assessed what the impact is of four economic variables in our model: fraction of GDP from the agriculture sector, fraction of GDP from the food and accommodation services sector, fraction of tourism that comes from abroad, and internet coverage. 

We found that the tourism-related variables impacted GDP loss for the No Closure strategy, which is because GDP losses will be suffered only in this sector when there is no mandated closure. This means the GDP loss will depend on the extent to which the economy is depending on this sector. We found that Education losses depend to some extent on internet coverage, because our model assumes that internet access can be used to mitigate losses by enabling remote learning. We found little effect of the size of the agricultural sector.

In parallel, we present a selection of other model parameters, including those related to demography (e.g. the fraction of the population who are of school age), to the economy (e.g. GDP), to the health system (e.g. hospital capacity), to the pandemic response (e.g. the rate of testing), and to the pathogen (e.g. the basic reproductive number, R$_0$). We found that these variables -- in combinations up to four -- account for much of the variability in outcomes. 

## The modelling framework

Ours is a mechanistic simulation model. The model encodes complex relationships between demographic, epidemic and economic variables. With simulation, it allows us to explore outcomes as consequences of inputs using information- and decision-theoretic methods. Modelling allows *in silico* experimentation, which is crucial for questions pertaining to rare events with small and confounded datasets, as cross-sectional country data are. The model allows us to ask questions about cause and effect that cannot be asked in reality and rarely can be inferred from observational data.

The challenge we face with modelling, then, is to be confident that our model mimics reality, or at least captures the elements with which we are concerned.

## The economic model

We have used a simple economic model that allows us to estimate GDP loss in a year assuming that sector closures follow mandates. The mandates we use are schematic and representative of GVA profiles seen in different countries in 2020.

The economic model is static, and does not take into account any dynamics such as feedback, changes to demand, supply and supply chains, changes in international trade, or any macroeconomic factors. As such, to model longer-term economic impacts (apart from the impact of lost education) is beyond the scope of this model.

For example, Figure \@ref(fig:gdpdata2) shows the relationship between GDP loss in the first year (2020) and GDP loss in the second year (2021) following the outbreak of COVID-19. There is heterogeneity in losses in the first year, but also in whether or not the economy recovers in the second year, and to what extent. The recovery is arguably a more important phenomenon to capture than initial losses, and it is not something that can be captured by our economic model. However, a model of recovery / future losses would include initial loss as an input, which our model could provide.

<div class="figure">
<img src="p2_files/figure-html/gdpdata2-1.png" alt="GDP loss and recovery. On the x axis is the GDP of 2020 relative to its 2019 projected value (IMF). On the y axis is 2021 GDP relative to its 2019 projected value relative to the same value for 2020 (ratio of ratios). x values below 100 represent a loss in the year 2020. y values above 0 represent recovery (i.e. growth exceeded what was expected in 2019); y values equal to zero represent a fixed level of loss; y values less than zero represent increasing loss."  />
<p class="caption">(\#fig:gdpdata2)GDP loss and recovery. On the x axis is the GDP of 2020 relative to its 2019 projected value (IMF). On the y axis is 2021 GDP relative to its 2019 projected value relative to the same value for 2020 (ratio of ratios). x values below 100 represent a loss in the year 2020. y values above 0 represent recovery (i.e. growth exceeded what was expected in 2019); y values equal to zero represent a fixed level of loss; y values less than zero represent increasing loss.</p>
</div>


(confirm with Patrick) GVA for a sector is reduced as a consequence of illness and death of workers, but not due to a reduction in demand (e.g. private/final consumption).

\newpage




# References

<div id="refs"></div>

\newpage

# Pathogen profiles

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>(\#tab:tabpp)Pathogen profiles. \label{tab:tabres}</caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> SARS </th>
   <th style="text-align:left;"> Flu2009 </th>
   <th style="text-align:left;"> Flu1957 </th>
   <th style="text-align:left;"> Flu1918 </th>
   <th style="text-align:left;"> CovidWT </th>
   <th style="text-align:left;"> CovidOM </th>
   <th style="text-align:left;"> CovidDE </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> IHR, ages 0-4, % </td>
   <td style="text-align:left;"> 5.8 </td>
   <td style="text-align:left;"> 0.47 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 0.0016 </td>
   <td style="text-align:left;"> 0.0033 </td>
   <td style="text-align:left;"> 0.003 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 5-9, % </td>
   <td style="text-align:left;"> 5.8 </td>
   <td style="text-align:left;"> 0.18 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 0.0016 </td>
   <td style="text-align:left;"> 0.0033 </td>
   <td style="text-align:left;"> 0.003 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 10-14, % </td>
   <td style="text-align:left;"> 5.8 </td>
   <td style="text-align:left;"> 0.18 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 2.6 </td>
   <td style="text-align:left;"> 0.041 </td>
   <td style="text-align:left;"> 0.059 </td>
   <td style="text-align:left;"> 0.075 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 15-19, % </td>
   <td style="text-align:left;"> 5.8 </td>
   <td style="text-align:left;"> 0.18 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 5.3 </td>
   <td style="text-align:left;"> 0.041 </td>
   <td style="text-align:left;"> 0.059 </td>
   <td style="text-align:left;"> 0.075 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 20-24, % </td>
   <td style="text-align:left;"> 8.2 </td>
   <td style="text-align:left;"> 0.18 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 9.1 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 0.83 </td>
   <td style="text-align:left;"> 1.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 25-29, % </td>
   <td style="text-align:left;"> 8.2 </td>
   <td style="text-align:left;"> 0.38 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 16 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 0.83 </td>
   <td style="text-align:left;"> 1.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 30-34, % </td>
   <td style="text-align:left;"> 8.2 </td>
   <td style="text-align:left;"> 0.38 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 13 </td>
   <td style="text-align:left;"> 3.4 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 6.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 35-39, % </td>
   <td style="text-align:left;"> 8.2 </td>
   <td style="text-align:left;"> 0.38 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 3.4 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 6.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 40-44, % </td>
   <td style="text-align:left;"> 30 </td>
   <td style="text-align:left;"> 0.38 </td>
   <td style="text-align:left;"> 0.09 </td>
   <td style="text-align:left;"> 8.8 </td>
   <td style="text-align:left;"> 4.2 </td>
   <td style="text-align:left;"> 1.6 </td>
   <td style="text-align:left;"> 7.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 45-49, % </td>
   <td style="text-align:left;"> 30 </td>
   <td style="text-align:left;"> 0.38 </td>
   <td style="text-align:left;"> 2.3 </td>
   <td style="text-align:left;"> 6.4 </td>
   <td style="text-align:left;"> 4.2 </td>
   <td style="text-align:left;"> 1.6 </td>
   <td style="text-align:left;"> 7.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 50-54, % </td>
   <td style="text-align:left;"> 30 </td>
   <td style="text-align:left;"> 0.71 </td>
   <td style="text-align:left;"> 2.3 </td>
   <td style="text-align:left;"> 8.8 </td>
   <td style="text-align:left;"> 8.2 </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 15 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 55-59, % </td>
   <td style="text-align:left;"> 30 </td>
   <td style="text-align:left;"> 0.71 </td>
   <td style="text-align:left;"> 2.3 </td>
   <td style="text-align:left;"> 6.3 </td>
   <td style="text-align:left;"> 8.2 </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 15 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 60-64, % </td>
   <td style="text-align:left;"> 87 </td>
   <td style="text-align:left;"> 0.71 </td>
   <td style="text-align:left;"> 2.3 </td>
   <td style="text-align:left;"> 16 </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 3.1 </td>
   <td style="text-align:left;"> 22 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 65-69, % </td>
   <td style="text-align:left;"> 87 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 18 </td>
   <td style="text-align:left;"> 22 </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 3.1 </td>
   <td style="text-align:left;"> 22 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 70-74, % </td>
   <td style="text-align:left;"> 87 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 18 </td>
   <td style="text-align:left;"> 26 </td>
   <td style="text-align:left;"> 17 </td>
   <td style="text-align:left;"> 6.1 </td>
   <td style="text-align:left;"> 31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 75-79, % </td>
   <td style="text-align:left;"> 87 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 18 </td>
   <td style="text-align:left;"> 26 </td>
   <td style="text-align:left;"> 17 </td>
   <td style="text-align:left;"> 6.1 </td>
   <td style="text-align:left;"> 31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IHR, ages 80-+, % </td>
   <td style="text-align:left;"> 60 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 18 </td>
   <td style="text-align:left;"> 26 </td>
   <td style="text-align:left;"> 18 </td>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;"> 34 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 0-4, % </td>
   <td style="text-align:left;"> 1.5 </td>
   <td style="text-align:left;"> 0.018 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 1.5 </td>
   <td style="text-align:left;"> 0.0016 </td>
   <td style="text-align:left;"> 0.0033 </td>
   <td style="text-align:left;"> 0.003 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 5-9, % </td>
   <td style="text-align:left;"> 1.5 </td>
   <td style="text-align:left;"> 0.0074 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 0.27 </td>
   <td style="text-align:left;"> 0.0016 </td>
   <td style="text-align:left;"> 0.0033 </td>
   <td style="text-align:left;"> 0.003 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 10-14, % </td>
   <td style="text-align:left;"> 1.5 </td>
   <td style="text-align:left;"> 0.0074 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 0.32 </td>
   <td style="text-align:left;"> 0.007 </td>
   <td style="text-align:left;"> 0.01 </td>
   <td style="text-align:left;"> 0.013 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 15-19, % </td>
   <td style="text-align:left;"> 1.5 </td>
   <td style="text-align:left;"> 0.008 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 0.66 </td>
   <td style="text-align:left;"> 0.007 </td>
   <td style="text-align:left;"> 0.01 </td>
   <td style="text-align:left;"> 0.013 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 20-24, % </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 0.008 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 1.1 </td>
   <td style="text-align:left;"> 0.031 </td>
   <td style="text-align:left;"> 0.025 </td>
   <td style="text-align:left;"> 0.057 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 25-29, % </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 0.02 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 0.031 </td>
   <td style="text-align:left;"> 0.025 </td>
   <td style="text-align:left;"> 0.057 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 30-34, % </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 0.02 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 1.7 </td>
   <td style="text-align:left;"> 0.084 </td>
   <td style="text-align:left;"> 0.048 </td>
   <td style="text-align:left;"> 0.16 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 35-39, % </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 0.02 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 1.5 </td>
   <td style="text-align:left;"> 0.084 </td>
   <td style="text-align:left;"> 0.048 </td>
   <td style="text-align:left;"> 0.16 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 40-44, % </td>
   <td style="text-align:left;"> 7.7 </td>
   <td style="text-align:left;"> 0.02 </td>
   <td style="text-align:left;"> 0.0067 </td>
   <td style="text-align:left;"> 1.1 </td>
   <td style="text-align:left;"> 0.16 </td>
   <td style="text-align:left;"> 0.06 </td>
   <td style="text-align:left;"> 0.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 45-49, % </td>
   <td style="text-align:left;"> 7.7 </td>
   <td style="text-align:left;"> 0.043 </td>
   <td style="text-align:left;"> 0.17 </td>
   <td style="text-align:left;"> 0.8 </td>
   <td style="text-align:left;"> 0.16 </td>
   <td style="text-align:left;"> 0.06 </td>
   <td style="text-align:left;"> 0.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 50-54, % </td>
   <td style="text-align:left;"> 7.7 </td>
   <td style="text-align:left;"> 0.043 </td>
   <td style="text-align:left;"> 0.17 </td>
   <td style="text-align:left;"> 1.1 </td>
   <td style="text-align:left;"> 0.6 </td>
   <td style="text-align:left;"> 0.15 </td>
   <td style="text-align:left;"> 1.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 55-59, % </td>
   <td style="text-align:left;"> 7.7 </td>
   <td style="text-align:left;"> 0.043 </td>
   <td style="text-align:left;"> 0.17 </td>
   <td style="text-align:left;"> 0.78 </td>
   <td style="text-align:left;"> 0.6 </td>
   <td style="text-align:left;"> 0.15 </td>
   <td style="text-align:left;"> 1.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 60-64, % </td>
   <td style="text-align:left;"> 22 </td>
   <td style="text-align:left;"> 0.043 </td>
   <td style="text-align:left;"> 0.17 </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 1.9 </td>
   <td style="text-align:left;"> 0.5 </td>
   <td style="text-align:left;"> 3.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 65-69, % </td>
   <td style="text-align:left;"> 22 </td>
   <td style="text-align:left;"> 0.66 </td>
   <td style="text-align:left;"> 1.3 </td>
   <td style="text-align:left;"> 2.8 </td>
   <td style="text-align:left;"> 1.9 </td>
   <td style="text-align:left;"> 0.5 </td>
   <td style="text-align:left;"> 3.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 70-74, % </td>
   <td style="text-align:left;"> 22 </td>
   <td style="text-align:left;"> 0.66 </td>
   <td style="text-align:left;"> 1.3 </td>
   <td style="text-align:left;"> 3.3 </td>
   <td style="text-align:left;"> 4.3 </td>
   <td style="text-align:left;"> 1.6 </td>
   <td style="text-align:left;"> 7.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 75-79, % </td>
   <td style="text-align:left;"> 22 </td>
   <td style="text-align:left;"> 0.66 </td>
   <td style="text-align:left;"> 1.3 </td>
   <td style="text-align:left;"> 3.3 </td>
   <td style="text-align:left;"> 4.3 </td>
   <td style="text-align:left;"> 1.6 </td>
   <td style="text-align:left;"> 7.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IFR, ages 80-+, % </td>
   <td style="text-align:left;"> 15 </td>
   <td style="text-align:left;"> 0.66 </td>
   <td style="text-align:left;"> 1.3 </td>
   <td style="text-align:left;"> 3.3 </td>
   <td style="text-align:left;"> 7.8 </td>
   <td style="text-align:left;"> 4.8 </td>
   <td style="text-align:left;"> 14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Probability asymptomatic </td>
   <td style="text-align:left;"> 0.87 </td>
   <td style="text-align:left;"> 0.67 </td>
   <td style="text-align:left;"> 0.67 </td>
   <td style="text-align:left;"> 0.67 </td>
   <td style="text-align:left;"> 0.6 </td>
   <td style="text-align:left;"> 0.6 </td>
   <td style="text-align:left;"> 0.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Latent period </td>
   <td style="text-align:left;"> 4.6 </td>
   <td style="text-align:left;"> 1.1 </td>
   <td style="text-align:left;"> 1.1 </td>
   <td style="text-align:left;"> 1.1 </td>
   <td style="text-align:left;"> 4.6 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Time to recovery (asymptomatic) </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 2.1 </td>
   <td style="text-align:left;"> 2.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Time to recovery (symptomatic) </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Time to hospitalisation </td>
   <td style="text-align:left;"> 3.8 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Time to recovery (hospital) </td>
   <td style="text-align:left;"> 23 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 5.5 </td>
   <td style="text-align:left;"> 7.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Time to death </td>
   <td style="text-align:left;"> 20 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 5.5 </td>
   <td style="text-align:left;"> 7.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Immunity waning </td>
   <td style="text-align:left;"> 360 </td>
   <td style="text-align:left;"> 360 </td>
   <td style="text-align:left;"> 360 </td>
   <td style="text-align:left;"> 360 </td>
   <td style="text-align:left;"> 360 </td>
   <td style="text-align:left;"> 360 </td>
   <td style="text-align:left;"> 360 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Reduced infectivity asymptomatic </td>
   <td style="text-align:left;"> 0.58 </td>
   <td style="text-align:left;"> 0.58 </td>
   <td style="text-align:left;"> 0.58 </td>
   <td style="text-align:left;"> 0.58 </td>
   <td style="text-align:left;"> 0.58 </td>
   <td style="text-align:left;"> 0.58 </td>
   <td style="text-align:left;"> 0.58 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R0 </td>
   <td style="text-align:left;"> 1.8 </td>
   <td style="text-align:left;"> 1.6 </td>
   <td style="text-align:left;"> 1.8 </td>
   <td style="text-align:left;"> 2.5 </td>
   <td style="text-align:left;"> 2.9 </td>
   <td style="text-align:left;"> 5.9 </td>
   <td style="text-align:left;"> 5.1 </td>
  </tr>
</tbody>
</table>


# Economic configurations

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>(\#tab:eccon)Economic configurations used to implement strategies. Values are the openness of the sector expressed as a percentage.  Elimination values are taken from Australia. Lockdown and Economic Closures values are taken from the UK. School Closures values are taken from Indonesia. \label{tab:eccon}</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Sector </th>
   <th style="text-align:right;"> Elimination </th>
   <th style="text-align:right;"> Lockdown </th>
   <th style="text-align:right;"> Economic Closures </th>
   <th style="text-align:right;"> Lockdown (School Closures) </th>
   <th style="text-align:right;"> School Closures </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Agriculture, hunting, forestry </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 86 </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fishing and aquaculture </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 86 </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mining and quarrying, energy producing products </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 67 </td>
   <td style="text-align:right;"> 79 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mining and quarrying, non-energy producing products </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mining support service activities </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Food products, beverages and tobacco </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Textiles, textile products, leather and footwear </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 89 </td>
   <td style="text-align:right;"> 92 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wood and products of wood and cork </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Paper products and printing </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Coke and refined petroleum products </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 87 </td>
   <td style="text-align:right;"> 88 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Chemical and chemical products </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Pharmaceuticals, medicinal chemical and botanical products </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rubber and plastics products </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 87 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Other non-metallic mineral products </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 89 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Basic metals </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fabricated metal products </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Computer, electronic and optical equipment </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Electrical equipment </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Machinery and equipment, nec </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 89 </td>
   <td style="text-align:right;"> 95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Motor vehicles, trailers and semi-trailers </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 66 </td>
   <td style="text-align:right;"> 82 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Other transport equipment </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 66 </td>
   <td style="text-align:right;"> 82 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Manufacturing nec; repair and installation of machinery and equipment </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Electricity, gas, steam and air conditioning supply </td>
   <td style="text-align:right;"> 97 </td>
   <td style="text-align:right;"> 89 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 94 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Water supply; sewerage, waste management and remediation activities </td>
   <td style="text-align:right;"> 97 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Construction </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 56 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 95 </td>
   <td style="text-align:right;"> 95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wholesale and retail trade; repair of motor vehicles </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 64 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 97 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Land transport and transport via pipelines </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 63 </td>
   <td style="text-align:right;"> 82 </td>
   <td style="text-align:right;"> 83 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Water transport </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 63 </td>
   <td style="text-align:right;"> 82 </td>
   <td style="text-align:right;"> 81 </td>
   <td style="text-align:right;"> 98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Air transport </td>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 63 </td>
   <td style="text-align:right;"> 82 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 42 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Warehousing and support activities for transportation </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 63 </td>
   <td style="text-align:right;"> 82 </td>
   <td style="text-align:right;"> 64 </td>
   <td style="text-align:right;"> 91 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Postal and courier activities </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 63 </td>
   <td style="text-align:right;"> 82 </td>
   <td style="text-align:right;"> 64 </td>
   <td style="text-align:right;"> 91 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Accommodation and food service activities </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 85 </td>
   <td style="text-align:right;"> 77 </td>
   <td style="text-align:right;"> 91 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Publishing, audiovisual and broadcasting activities </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Telecommunications </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IT and other information services </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 91 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Financial and insurance activities </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 96 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Real estate activities </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 98 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Professional, scientific and technical activities </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 85 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Administrative and support services </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 66 </td>
   <td style="text-align:right;"> 80 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Public administration and defence; compulsory social security </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 96 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Education </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Human health and social work activities </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 75 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Arts, entertainment and recreation </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 55 </td>
   <td style="text-align:right;"> 71 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Other service activities </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 54 </td>
   <td style="text-align:right;"> 83 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 49 </td>
   <td style="text-align:right;"> 53 </td>
   <td style="text-align:right;"> 90 </td>
   <td style="text-align:right;"> 96 </td>
  </tr>
</tbody>
</table>


# Methodological developments specific to this application

This work is based on a model currently under development. In this section we detail features added specifically to address the question of what is the impact of certain parameters on outcomes as encoded by our model.

## Impact of tourism


### Food and accommodation services sector

As there is no "tourism" sector in the 45-sector classification we are using, to model the impact of changes to tourism, we identify the "Food and accommodation services" sector with tourism. This is imperfect. The correlation of their % contributions to GDP is 0.64 and the order of magnitude is similar (1 to 7% vs 2 to 10% of GDP). The other two sectors considered (Air transport and Arts, entertainment and recreation) have little correlation with tourism in terms of % of GDP. (See Figure \@ref(fig:pairs).)



<div class="figure" style="text-align: center">
<img src="p2_files/figure-html/pairs-1.png" alt="Correlations between tourism-related data. First: https://www.unwto.org/tourism-statistics/key-tourism-statistics. Second to fourth: https://www.unwto.org/tourism-data/international-tourism-and-covid-19. Fifth to seventh: OECD."  />
<p class="caption">(\#fig:pairs)Correlations between tourism-related data. First: https://www.unwto.org/tourism-statistics/key-tourism-statistics. Second to fourth: https://www.unwto.org/tourism-data/international-tourism-and-covid-19. Fifth to seventh: OECD.</p>
</div>


\newpage


### Sector shrinkage as a result of the pandemic






For many countries, tourism was reduced not because of domestic mandates but because of reduced international travel. Therefore, the fraction of tourism that comes from abroad is a factor that can determine the impact of a pandemic on a country's GDP potentially independently of what happens within the country. (A useful model extension would be to include some dependence on country factors, e.g. case numbers.)

We model mitigation via business closures, which are mandated by sector. We represent openness with values $x$ which range from 0 to 1, 1 representing maximum openness. To capture the impact of reduced international travel, we set the maximum openness of the food and accommodation services sector to be limited by international tourism as:

$$x_\tau = \min\{\hat{x}_\tau, 1+ y(z-1)\}$$

where $\hat{x}_\tau$ is the openness of the sector at time $\tau$ according to the schedule (i.e. the mitigation strategy), $y$ is the proportion of tourism that is international, and $z$ is the fraction international tourism reduces to as a consequence of the pandemic. I.e. the tourism remaining is the domestic ($1-y$) plus that that comes in from abroad ($yz$).

Therefore, the contribution of the GVA of the food and accommodation services sector is limited either by the pandemic, or by the mitigation measures - whichever is lower.








### Loss of international tourists

We model the distribution of $z$ using data from 2020 (Figure \@ref(fig:tourismhist), bottom-right plot). We fit to it a log-normal distribution, and find mean value -1.39 and standard deviation 0.39 (Figure \@ref(fig:ytd)). We use these values as inputs for all country models.


<div class="figure" style="text-align: center">
<img src="p2_files/figure-html/tourismhist-1.png" alt="Distributions of tourism-related data from https://www.unwto.org/tourism-data/international-tourism-and-covid-19. In grey are the subset of countries for which we have GVA data by sector."  />
<p class="caption">(\#fig:tourismhist)Distributions of tourism-related data from https://www.unwto.org/tourism-data/international-tourism-and-covid-19. In grey are the subset of countries for which we have GVA data by sector.</p>
</div>


<div class="figure" style="text-align: center">
<img src="p2_files/figure-html/ytd-1.png" alt="Fit of log-normal distribution to loss-of-tourism data."  />
<p class="caption">(\#fig:ytd)Fit of log-normal distribution to loss-of-tourism data.</p>
</div>



\newpage


### Dependence on international tourism

We model $y$ as a function of the share of GDP that comes from the sector. Note that the data we have for this are biased towards high-income countries.

We write 

$$y\sim\text{Beta}(\alpha(u),\beta(u))$$

where $u$ is the fraction of GDP coming from the Food and accommodation sector. We learn three parameters $p_1$, $p_2$ and $p_3$ to best fit the relationship between $u$ and $y$ in countries we have observations for:

$$p_1 = \alpha(u)+\beta(u)$$

$$p_2u + p_3 = \frac{\alpha(u)}{\alpha(u)+\beta(u)}$$
  
Here, $p_1$ controls the variance of the distribution and $p_2$ and $p_3$ the linear relationship between $u$ and $y$. Using an optimisation routine in R we find $p_1=5.93$, $p_2=3.66$ and $p_3=0.099$. Results are shown in Figure \@ref(fig:sectortourism). We use these values as inputs for all country models.

 ![(\#fig:sectortourism) Predicting the percentage of tourism that comes from abroad as a function of the size of the sector. Each row represents a beta distribution whose mean is determined by the size of the sector (u). Blue points show the data we have available (grey bars in Figure \@ref(fig:tourismhist)).](figures/sectortourism.png){ width=60% }

\newpage


## Sampling sector sizes

To learn about the impacts of changes to sector sizes, we use the following process to sample a baseline economic configuration.

1. Sample a population distribution from all countries (within income group)
2. Sample new values for the population proportions of the Food and accommodation services and Agricultural workforces from uniform distributions bounded by the limits of the dataset
3. Scale the remaining sectors up or down proportionally to match the original total population size.



## Impact of sector sizes

The distribution of people among sectors of the workforce impacts the numbers of contacts made. In order to propagate these influences through the model, we sample a null distribution of contacts from the generating model and save the corresponding average number of candidate infectees (CI, where CI $=R_0/\beta$). Separately, we define a distribution over R$_0$, e.g. a normal distribution with its stated mean value and a coefficient of variation of 0.1. (E.g. for H1N1, with mean 1.58, the standard deviation given 95% interval {1.34, 2.04} is 0.18 which is a coefficient of variation of 0.11 [@Fraser2009].) Then, for each simulation, we compute the quantile of the CI distribution corresponding to the contacts generated, and select the corresponding quantile from the R$_0$ distribution. Shown illustratively in Figure \@ref(fig:candidateinfectees).



 ![(\#fig:candidateinfectees) The number of candidate infectees is mapped to the basic reproduction number $R_0$ via matching quantiles from the simulated null distribution (left) to the parametric distribution (right). 10, 50 and 90% quantiles shown.](figures/candidateinfectees.png){ width=80% }


\newpage


## Internet infrastructure


For each sector in each country, we have the 90% interval for the proportion of people who can work from home from [@Gottlieb2021]. We assume that the value we sample within the range is related to internet infrastructure, so that a low value in one sector implies low values in all sectors. We:

- Take the subset of countries in the income group (LLMIC / MIC / HIC)
- Take the minimum of the lower bounds by sector (5%)
- Take the maximum of the upper bounds by sector (95%)
- Sample from a uniform distribution between these bounds, taking the same quantile for each sector
- Use the same quantile again for internet coverage in computing the effectiveness of remote learning


### Remote teaching

For the value of a year of education, we use the method of [@Psacharopoulos2021a]. The loss due to school closure is

$$L = \text{PV}\cdot Y\cdot \alpha\cdot r\cdot S\cdot \beta$$

where PV is the present value of lost earnings:

$$\text{PV} =  \frac{1-(1+d)^{-n}}{d}$$

for discount rate $d=0.03$ and expected number of years of work $n=45$. $Y$ is mean annual earnings, $\alpha$ is the fraction of the year schools are closed: $$\alpha=\frac{1}{12}\sum_{\tau=1}^{12}1-x_{ed,\tau},$$ $r=0.08$ is the rate of return for one year, $S$ is the total number of students, and $\beta$ is the proportion of students affected. We take $\beta=1-0.86I$ to be the complement fraction of internet coverage $I$ (Figure \@ref(fig:internet)) multiplied by 0.86, to match values for the Philippines: it has 43% internet coverage and effectiveness of remote education was estimated to be 37% [@NationalEconomicandDevelopmentAuthority2021].

<div class="figure">
<img src="p2_files/figure-html/internet-1.png" alt="Internet access by income level. World Bank data for 2019."  />
<p class="caption">(\#fig:internet)Internet access by income level. World Bank data for 2019.</p>
</div>

We model the Figure \@ref(fig:internet) values with Beta distributions. For LLMICs, we have parameters 1.78 and  3.11. For MICs, we have parameters 3.77 and  2.91. For HICs, we have parameters 9.57 and  1.39.




We estimate the average annual income per working-age adult as the total GVA multiplied by the fraction of GVA that goes to labour divided by the number of working-age adults. For the fraction of GVA that goes to labour we use PWT estimates from 2011 (Figure \@ref(fig:labsh)). (This correction might lead us to underestimate the impact of education: perhaps GNI per working-age adult is better than average income among working-age adults. E.g. suppose Country A and Country B have the same GVA and the same number of workers, where GVA = labour compensation + capital. And suppose Country A splits its GVA between labour and capital with ratio 1:2, and Country B with ratio 2:1. Then the value of education in Country B is twice that in Country A, because we are only counting the income contribution to the economy. If we wanted to estimate the impact on the economy, we should use the whole GVA, not just the labour share.)

<!-- For the value of a year of education, we use results from [@Psacharopoulos2021a]. For an LIC, the cost of a lost school year is 207% of GDP. For a MIC, the cost of a lost school year is 73% of GDP. For an HIC, the cost of a lost school year is 30% of GDP. -->

<div class="figure">
<img src="p2_files/figure-html/labsh-1.png" alt="Fraction of GVA that goes to labour (PWT, 2011)."  />
<p class="caption">(\#fig:labsh)Fraction of GVA that goes to labour (PWT, 2011).</p>
</div>

We model these values with Beta distributions. For LLMICs, we have parameters 5.09 and  4.51. For MICs, we have parameters 6.29 and  6.54. For HICs, we have parameters 7.97 and  6.87.

\newpage

## Hospital capacity

<div class="figure">
<img src="p2_files/figure-html/hmax-1.png" alt="Fraction of GVA that goes to labour (PWT, 2011)."  />
<p class="caption">(\#fig:hmax)Fraction of GVA that goes to labour (PWT, 2011).</p>
</div>

We model these values with gamma distributions. For LLMICs, we have parameters 1.3 and  0.05. For MICs, we have parameters 1.36 and  0.03. For HICs, we have parameters 2.05 and  0.02.


\newpage

# Comparison of model results for SARS-CoV-2 (pre-Alpha) to 2020 data

Our model has not been calibrated to fit any observed economic outcomes in general or for any specific country. However, the distributions for the pre-Alpha profile of SARS-CoV-2 should align to some extent with data pertaining to 2020, as many of the inputs to the model were taken from this period.

## GDP loss

<div class="figure">
<img src="p2_files/figure-html/gdpdata-1.png" alt="GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF). NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries. The outlier is Guyana."  />
<p class="caption">(\#fig:gdpdata)GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF). NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries. The outlier is Guyana.</p>
</div>

<div class="figure">
<img src="p2_files/figure-html/gdpdatallmic-1.png" alt="GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF) for low- and lower-middle-income countries with densities from the model shown by strategy. NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries."  />
<p class="caption">(\#fig:gdpdatallmic)GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF) for low- and lower-middle-income countries with densities from the model shown by strategy. NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries.</p>
</div>

<div class="figure">
<img src="p2_files/figure-html/gdpdatamic-1.png" alt="GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF) for upper- and lower-middle-income countries with densities from the model shown by strategy. NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries. The outlier is Guyana."  />
<p class="caption">(\#fig:gdpdatamic)GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF) for upper- and lower-middle-income countries with densities from the model shown by strategy. NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries. The outlier is Guyana.</p>
</div>

<div class="figure">
<img src="p2_files/figure-html/gdpdatahic-1.png" alt="GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF) for high-income countries with densities from the model shown by strategy. NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries."  />
<p class="caption">(\#fig:gdpdatahic)GDP loss: loss in 2020 as a percentage of 2019 GDP (IMF) for high-income countries with densities from the model shown by strategy. NB: data are annual, so the loss is for the year starting January 2020. We would prefer to present data for April 2020 to March 2021 but these data are unavailable for most countries.</p>
</div>



\newpage


## School closure

<div class="figure">
<img src="p2_files/figure-html/schooldata-1.png" alt="Extent of school closure. Horizontal lines (one per country) show the duration of the first year spent with schools partially closed. The space to the left of the line represents the duration schools were open. The space to the right of the line represents the duration schools were closed. (UNESCO)"  />
<p class="caption">(\#fig:schooldata)Extent of school closure. Horizontal lines (one per country) show the duration of the first year spent with schools partially closed. The space to the left of the line represents the duration schools were open. The space to the right of the line represents the duration schools were closed. (UNESCO)</p>
</div>


\newpage

## Value of lives lost

<div class="figure">
<img src="p2_files/figure-html/lives-1.png" alt="Valued loss of life, using IHME estimates (&quot;cumulative deaths&quot;) for the first year of accumulated deaths. The value of a statistical life used is 160 times GDP per capita. (This means that a 0.625% mortality rate is worth 100% of GDP.)"  />
<p class="caption">(\#fig:lives)Valued loss of life, using IHME estimates ("cumulative deaths") for the first year of accumulated deaths. The value of a statistical life used is 160 times GDP per capita. (This means that a 0.625% mortality rate is worth 100% of GDP.)</p>
</div>

\newpage


# Pathogen profiles

## Parameters from Pandemic Potential, plus seven P2 profiles

![Profiles from the game Pandemic Potential](figures/pandemicprofiles.png)

![Profiles made using distribution from game](figures/pathogenprofilessynth.png)


![Intensity and frequency of extreme novel epidemics, Marani et al., PNAS, 2021](figures/marani2021.png)

\newpage

## Infection-hospitalisation rate (IHR)

![IHR by age for seven P2 pathogen profiles](figures/trainingihr.png)

![Posterior samples for seven P2 pathogen IHR profiles](figures/pathogenplot.png)

![Posterior distributions for IHR smooths](figures/pairsplot.png)

![New IHR samples for synthetic pathogens](figures/samplelogplot.png)

\newpage


## Hospital-fatality rate (HFR)

![HFR by age for seven P2 pathogen profiles](figures/traininghfr.png)

![Posterior samples for seven P2 pathogen HFR profiles](figures/pathogenplothfr.png)

![Posterior distributions for HFR smooths](figures/pairsplothfr.png)

![New HFR samples for synthetic pathogens](figures/samplelogplothfr.png)

\newpage

# Population health

From the Mexico BMI work, we can model disease transition rates as depending on population mean BMI. There are data available for many countries (though some are very old).

We could use a linear model with boundaries beyond which there is no further change. The range in population mean BMI in the Mexico scenarios (excluding the no-obesity scenario) was 26.9 to 28.9. Therefore we could extrapolate to 25.9 and 29.9, and assume fixed after that?

Writing relative risk $RR_{a,t} \sim \mathcal{N}(m_{a,t}\cdot \text{BMI} + c_{a,t},\sigma_{a,t}^2)$ for age groups $a$ and transitions $t$:

| Age group | Transition | $m$ | $c$ | $\sigma$ |
|:---- |:---- |:---- |:---- |:---- |
| 20-64 | Infection | 0.0166 | 0.524 | 0.00185 |
| 20-64 | Hospitalisation | 0.0518 | -0.484 | 0.00501 |
| 20-64 | Death | 0.0534 | -0.531 | 0.0168 |
| 65 plus | Infection | 0.00450 | 0.872 | 0.00155 |
| 65 plus | Hospitalisation | 0.0260 | 0.254 | 0.00590 |
| 65 plus | Death | 0.0111 | 0.680 | 0.0121 |


<div class="figure">
<img src="p2_files/figure-html/bmi-1.png" alt="Distributions of mean BMI among adults by country income level."  />
<p class="caption">(\#fig:bmi)Distributions of mean BMI among adults by country income level.</p>
</div>

We model these values with normal distributions. For LLMICs, we have mean and standard deviation parameters 24.29 and  2.28. For MICs, we have parameters 25.96 and  2.22. For HICs, we have parameters 26.81 and  1.52.



# Hospital fatality rate

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7685049/

Mean (min, max)

|  | LIC | LMIC | UMIC | HIC |
|:---- |:---- |:---- |:---- |:---- |
| ACBs per hundred thousand | 425 | 439 (334, 613) | 424.75 (210, 866) | 402.32 (190, 1119)|
| ICU bed per hundred thousand | 6.44 (0.03, 65) | 2.05 (0.03, 15) | 9.23 (0.16, 57) | 12.79 (1.8, 86) |



 In regards to World Bank Income Regions, low-income regions had a mean of 6.44 ICU bed/100,000 (maximum = 65, minimum = 0.03, range = 64.97, SD = 19.45), lower middle-income regions had a mean of 2.05 ICU beds/100,000 (maximum = 15, minimum = 0.03, range = 14.97, SD = 3.54), upper middle-income regions had a mean of 9.23 ICU beds/100,000 (maximum = 57, minimum = 0.16, range = 56.84, SD = 13.60) and high-income regions had a mean of 12.79 ICU beds/100,000 (maximum = 86, minimum = 1.8, range = 84.2, SD = 14.57).
